-- PostgreSQL foundation schema baseline for durable server-side data.
-- Later changes will add migration jobs, cutover logic, embeddings, and
-- stricter data-access policies.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'member',
  status TEXT NOT NULL DEFAULT 'pending',
  token_version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  approved_by TEXT,
  last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  num INTEGER NOT NULL DEFAULT 0,
  date TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Evaluated',
  pdf_generated INTEGER NOT NULL DEFAULT 0,
  report_path TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, company, role)
);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  report_num INTEGER NOT NULL,
  date TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  archetype TEXT NOT NULL DEFAULT '',
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  legitimacy TEXT NOT NULL DEFAULT '',
  blocks_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_hash TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, report_num)
);

CREATE INDEX IF NOT EXISTS idx_reports_source_hash ON reports(source_hash);

CREATE TABLE IF NOT EXISTS jds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  source_type TEXT NOT NULL DEFAULT 'paste',
  source_url TEXT,
  body TEXT NOT NULL DEFAULT '',
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  report_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE SEQUENCE IF NOT EXISTS profiles_id_seq;

CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT PRIMARY KEY DEFAULT nextval('profiles_id_seq'),
  user_id TEXT REFERENCES users(id),
  data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  goals_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  history_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS profile_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  source TEXT NOT NULL DEFAULT 'dingwei',
  signal_type TEXT NOT NULL,
  content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  session_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_profile_signals_type ON profile_signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_profile_signals_created ON profile_signals(created_at);

CREATE TABLE IF NOT EXISTS reference_resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  name TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'paste',
  sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_text TEXT NOT NULL DEFAULT '',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS optimization_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  section_id TEXT NOT NULL,
  variant_type TEXT NOT NULL,
  action TEXT NOT NULL,
  original_text TEXT,
  optimized_text TEXT,
  operation TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_opt_prefs_created ON optimization_preferences(created_at);

CREATE TABLE IF NOT EXISTS news_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  source_name TEXT,
  title TEXT NOT NULL,
  summary TEXT,
  url TEXT,
  published_at TIMESTAMPTZ,
  cached_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_cache_source ON news_cache(source);
CREATE INDEX IF NOT EXISTS idx_news_cache_cached ON news_cache(cached_at);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL DEFAULT '新对话',
  messages_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  memory_digest TEXT,
  interview_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  agent_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_updated ON sessions(updated_at);

CREATE SEQUENCE IF NOT EXISTS cv_data_id_seq;

CREATE TABLE IF NOT EXISTS cv_data (
  id BIGINT PRIMARY KEY DEFAULT nextval('cv_data_id_seq'),
  user_id TEXT REFERENCES users(id),
  data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  monthly_salary DOUBLE PRECISION NOT NULL DEFAULT 0,
  months_per_year INTEGER NOT NULL DEFAULT 12,
  annual_bonus DOUBLE PRECISION DEFAULT 0,
  has_social_insurance INTEGER NOT NULL DEFAULT 1,
  housing_fund_rate INTEGER NOT NULL DEFAULT 7,
  options TEXT,
  probation_months INTEGER NOT NULL DEFAULT 3,
  start_date TEXT,
  other_benefits TEXT,
  location TEXT,
  level TEXT,
  employment_form TEXT NOT NULL DEFAULT 'unknown',
  employer_name TEXT,
  contract_months INTEGER,
  overtime_policy TEXT NOT NULL DEFAULT 'unknown',
  bonus_guarantee TEXT NOT NULL DEFAULT 'unknown',
  equity_type TEXT,
  equity_vesting TEXT,
  commute_minutes INTEGER,
  city_cost_level TEXT NOT NULL DEFAULT 'unknown',
  job_nature TEXT,
  benefits_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  application_id BIGINT REFERENCES applications(id),
  latest_report_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, company, role)
);

CREATE TABLE IF NOT EXISTS offer_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL DEFAULT 'Offer 对比报告',
  report_type TEXT NOT NULL DEFAULT 'comparison',
  model_version TEXT NOT NULL DEFAULT '',
  offer_id BIGINT REFERENCES offers(id),
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  verdict TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  offer_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  modules_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  red_flags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  missing_info_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  negotiation_levers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  hr_questions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  assumptions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  take_home_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  offers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  report_markdown TEXT NOT NULL DEFAULT '',
  num_offers INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_offer_reports_offer ON offer_reports(offer_id, created_at);

CREATE TABLE IF NOT EXISTS stories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL,
  situation TEXT NOT NULL DEFAULT '',
  task TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT '',
  result TEXT NOT NULL DEFAULT '',
  tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  entity_type TEXT NOT NULL,
  entity_key TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  decay_rate DOUBLE PRECISION NOT NULL DEFAULT 0.05,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, entity_type, entity_key)
);

CREATE INDEX IF NOT EXISTS idx_agent_prefs_type ON agent_preferences(entity_type);

CREATE TABLE IF NOT EXISTS session_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  session_id BIGINT DEFAULT 0,
  summary_type TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_session_memory_type ON session_memory(summary_type);

CREATE TABLE IF NOT EXISTS scan_queue (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  status TEXT DEFAULT 'pending',
  title_positive_json JSONB DEFAULT '[]'::jsonb,
  title_negative_json JSONB DEFAULT '[]'::jsonb,
  location_filter TEXT DEFAULT '',
  max_results INTEGER DEFAULT 50,
  companies_total INTEGER DEFAULT 0,
  companies_done INTEGER DEFAULT 0,
  jobs_found INTEGER DEFAULT 0,
  jobs_new INTEGER DEFAULT 0,
  error_log JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS scan_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id TEXT NOT NULL REFERENCES scan_queue(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  jd_id BIGINT REFERENCES jds(id),
  company TEXT NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  location TEXT DEFAULT '',
  department TEXT DEFAULT '',
  jd_snippet TEXT DEFAULT '',
  status TEXT DEFAULT 'new',
  last_error TEXT DEFAULT '',
  dedup_key TEXT NOT NULL UNIQUE,
  first_seen_at TIMESTAMPTZ DEFAULT now(),
  last_interaction_at TIMESTAMPTZ,
  discovered_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_scan_jobs_user_status ON scan_jobs(user_id, status);
CREATE INDEX IF NOT EXISTS idx_scan_jobs_scan ON scan_jobs(scan_id);
CREATE INDEX IF NOT EXISTS idx_scan_jobs_jd ON scan_jobs(jd_id);
CREATE INDEX IF NOT EXISTS idx_scan_queue_user ON scan_queue(user_id, status);

ALTER TABLE profiles ALTER COLUMN id SET DEFAULT nextval('profiles_id_seq');
ALTER SEQUENCE profiles_id_seq OWNED BY profiles.id;
SELECT setval('profiles_id_seq', COALESCE((SELECT MAX(id) FROM profiles), 0) + 1, false);

ALTER TABLE cv_data ALTER COLUMN id SET DEFAULT nextval('cv_data_id_seq');
ALTER SEQUENCE cv_data_id_seq OWNED BY cv_data.id;
SELECT setval('cv_data_id_seq', COALESCE((SELECT MAX(id) FROM cv_data), 0) + 1, false);

ALTER TABLE jds DROP CONSTRAINT IF EXISTS jds_report_id_fkey;
ALTER TABLE reports DROP CONSTRAINT IF EXISTS reports_report_num_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reports_user_report_num_key'
      AND conrelid = 'reports'::regclass
  ) THEN
    ALTER TABLE reports ADD CONSTRAINT reports_user_report_num_key UNIQUE (user_id, report_num);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'profiles_user_id_key'
      AND conrelid = 'profiles'::regclass
  ) THEN
    ALTER TABLE profiles ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cv_data_user_id_key'
      AND conrelid = 'cv_data'::regclass
  ) THEN
    ALTER TABLE cv_data ADD CONSTRAINT cv_data_user_id_key UNIQUE (user_id);
  END IF;
END $$;
