-- PostgreSQL foundation schema baseline for durable server-side data.
-- Later changes will add migration jobs, cutover logic, embeddings, and
-- stricter data-access policies.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'member',
  status TEXT NOT NULL DEFAULT 'pending',
  token_version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  approved_by TEXT,
  last_login_at TIMESTAMPTZ,
  password_changed_at TIMESTAMPTZ,
  password_changed_by TEXT,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  last_security_event_at TIMESTAMPTZ
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_by TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_security_event_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS auth_security_events (
  id TEXT PRIMARY KEY,
  event_type TEXT NOT NULL,
  actor_user_id TEXT,
  target_user_id TEXT,
  actor_role TEXT,
  outcome TEXT NOT NULL,
  reason_code TEXT,
  request_id TEXT NOT NULL,
  source_ip TEXT,
  user_agent TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_security_events_type
  ON auth_security_events(event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_security_events_actor
  ON auth_security_events(actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_security_events_target
  ON auth_security_events(target_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_security_events_request
  ON auth_security_events(request_id);

CREATE OR REPLACE FUNCTION reject_auth_security_event_mutation()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'auth_security_events is append-only';
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'auth_security_events_no_mutation'
  ) THEN
    CREATE TRIGGER auth_security_events_no_mutation
    BEFORE UPDATE OR DELETE ON auth_security_events
    FOR EACH ROW EXECUTE FUNCTION reject_auth_security_event_mutation();
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS password_recovery_requests (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  source_ip TEXT,
  user_agent TEXT,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  resolved_by TEXT,
  resolution TEXT,
  CHECK (status IN ('pending', 'completed', 'dismissed'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_password_recovery_one_pending_per_user
  ON password_recovery_requests(user_id) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_password_recovery_pending
  ON password_recovery_requests(status, requested_at DESC);

CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  num INTEGER NOT NULL DEFAULT 0,
  date TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'evaluated',
  pdf_generated INTEGER NOT NULL DEFAULT 0,
  report_path TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  jd_id BIGINT,
  source_url TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, company, role)
);

ALTER TABLE applications ADD COLUMN IF NOT EXISTS jd_id BIGINT;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE applications ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS application_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL DEFAULT 'note',
  from_status TEXT,
  to_status TEXT,
  note TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'system',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_application_events_user_app ON application_events(user_id, application_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_application_events_type ON application_events(user_id, event_type, created_at DESC);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  report_num INTEGER NOT NULL,
  date TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  archetype TEXT NOT NULL DEFAULT '',
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  legitimacy TEXT NOT NULL DEFAULT '',
  blocks_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_hash TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, report_num)
);

CREATE INDEX IF NOT EXISTS idx_reports_source_hash ON reports(source_hash);

CREATE TABLE IF NOT EXISTS jds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  source_type TEXT NOT NULL DEFAULT 'paste',
  source_url TEXT,
  body TEXT NOT NULL DEFAULT '',
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  report_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE SEQUENCE IF NOT EXISTS profiles_id_seq;

CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT PRIMARY KEY DEFAULT nextval('profiles_id_seq'),
  user_id TEXT REFERENCES users(id),
  data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  goals_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  history_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS profile_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  source TEXT NOT NULL DEFAULT 'dingwei',
  signal_type TEXT NOT NULL,
  content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  session_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_profile_signals_type ON profile_signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_profile_signals_created ON profile_signals(created_at);

CREATE TABLE IF NOT EXISTS reference_resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  name TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'paste',
  sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_text TEXT NOT NULL DEFAULT '',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  notes TEXT NOT NULL DEFAULT '',
  role_category TEXT NOT NULL DEFAULT '',
  industry_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  seniority TEXT NOT NULL DEFAULT '',
  visibility TEXT NOT NULL DEFAULT 'private',
  status TEXT NOT NULL DEFAULT 'active',
  quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  anonymized BOOLEAN NOT NULL DEFAULT FALSE,
  shared_text_redacted TEXT NOT NULL DEFAULT '',
  source_hash TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  approved_by TEXT REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reference_resumes_user ON reference_resumes(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS reference_resume_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_resume_id BIGINT NOT NULL REFERENCES reference_resumes(id) ON DELETE CASCADE,
  owner_user_id TEXT REFERENCES users(id),
  visibility TEXT NOT NULL DEFAULT 'private',
  status TEXT NOT NULL DEFAULT 'active',
  role_category TEXT NOT NULL DEFAULT '',
  section_type TEXT NOT NULL DEFAULT '',
  chunk_index INTEGER NOT NULL DEFAULT 0,
  chunk_text TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  embedding_model TEXT NOT NULL DEFAULT '',
  embedding_dimension INTEGER NOT NULL DEFAULT 1536,
  embedding vector(1536),
  embedding_status TEXT NOT NULL DEFAULT 'pending',
  failure_reason TEXT NOT NULL DEFAULT '',
  retry_count INTEGER NOT NULL DEFAULT 0,
  quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT reference_resume_chunks_status_check CHECK (embedding_status IN ('pending', 'embedded', 'failed', 'skipped')),
  CONSTRAINT reference_resume_chunks_dimension_check CHECK (embedding_dimension = 1536),
  UNIQUE (reference_resume_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_reference_resume_chunks_owner ON reference_resume_chunks(owner_user_id, role_category, status);
CREATE INDEX IF NOT EXISTS idx_reference_resume_chunks_shared ON reference_resume_chunks(visibility, status, role_category);
CREATE INDEX IF NOT EXISTS idx_reference_resume_chunks_embedding ON reference_resume_chunks(embedding_status, updated_at DESC);

CREATE TABLE IF NOT EXISTS reference_resume_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_resume_id BIGINT NOT NULL REFERENCES reference_resumes(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id),
  task_type TEXT NOT NULL DEFAULT 'cv_optimize',
  target_jd_id BIGINT,
  accepted BOOLEAN,
  feedback TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reference_resume_usage_resume ON reference_resume_usage(reference_resume_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reference_resume_usage_user ON reference_resume_usage(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS optimization_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  section_id TEXT NOT NULL,
  variant_type TEXT NOT NULL,
  action TEXT NOT NULL,
  original_text TEXT,
  optimized_text TEXT,
  operation TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_opt_prefs_created ON optimization_preferences(created_at);

CREATE TABLE IF NOT EXISTS resume_edit_proposals (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  section_id TEXT NOT NULL,
  base_version TEXT NOT NULL DEFAULT '',
  base_hash TEXT NOT NULL DEFAULT '',
  original_content TEXT NOT NULL DEFAULT '',
  proposed_content TEXT NOT NULL DEFAULT '',
  proposed_hash TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  risk_flags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resume_edit_proposals_status_check CHECK (status IN ('pending', 'applied', 'discarded', 'stale', 'rolled_back'))
);

CREATE INDEX IF NOT EXISTS idx_resume_edit_proposals_user_status ON resume_edit_proposals(user_id, status, updated_at DESC);

ALTER TABLE resume_edit_proposals DROP CONSTRAINT IF EXISTS resume_edit_proposals_status_check;
ALTER TABLE resume_edit_proposals ADD CONSTRAINT resume_edit_proposals_status_check
  CHECK (status IN ('pending', 'applied', 'discarded', 'stale', 'rolled_back'));

CREATE TABLE IF NOT EXISTS news_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  source_name TEXT,
  title TEXT NOT NULL,
  summary TEXT,
  url TEXT,
  published_at TIMESTAMPTZ,
  cached_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_cache_source ON news_cache(source);
CREATE INDEX IF NOT EXISTS idx_news_cache_cached ON news_cache(cached_at);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL DEFAULT '新对话',
  messages_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  memory_digest TEXT,
  interview_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  agent_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_updated ON sessions(updated_at);

CREATE TABLE IF NOT EXISTS agent_runs (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  session_id BIGINT REFERENCES sessions(id),
  task_type TEXT NOT NULL,
  agent_id TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'planned',
  contract_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_runs_status_check CHECK (
    status IN ('planned', 'running', 'waiting_user', 'verifying', 'repairing', 'recovered', 'needs_engineering', 'succeeded', 'failed', 'rolled_back', 'cancelled')
  )
);

ALTER TABLE agent_runs DROP CONSTRAINT IF EXISTS agent_runs_status_check;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS request_id TEXT;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS runtime_mode TEXT NOT NULL DEFAULT 'legacy';
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS execution_owner TEXT NOT NULL DEFAULT 'legacy';
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS snapshot_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS event_sequence BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS policy_versions_json JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS owner_id TEXT;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMPTZ;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS heartbeat_at TIMESTAMPTZ;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS fencing_token BIGINT NOT NULL DEFAULT 0;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS budgets_json JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS wake_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS legacy BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS parent_run_id TEXT REFERENCES agent_runs(id) ON DELETE SET NULL;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS depth INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS cancel_requested_at TIMESTAMPTZ;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS last_observation_json JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS isolation_requested_at TIMESTAMPTZ;
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS isolation_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS retention_expires_at TIMESTAMPTZ;
ALTER TABLE agent_runs ADD CONSTRAINT agent_runs_status_check CHECK (
  legacy = TRUE OR status IN ('queued', 'running', 'waiting_user', 'paused', 'recovering', 'verifying', 'cancel_requested', 'succeeded', 'failed', 'cancelled')
);

ALTER TABLE agent_runs DROP CONSTRAINT IF EXISTS agent_runs_user_id_fkey;
ALTER TABLE agent_runs
  ADD CONSTRAINT agent_runs_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_runs_request_id
  ON agent_runs(user_id, request_id)
  WHERE request_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_runs_one_active_conversation
  ON agent_runs(user_id, session_id)
  WHERE legacy = FALSE
    AND session_id IS NOT NULL
    AND status IN ('queued', 'running', 'waiting_user', 'recovering', 'verifying', 'cancel_requested');
CREATE INDEX IF NOT EXISTS idx_agent_runs_claim
  ON agent_runs(wake_at, created_at)
  WHERE legacy = FALSE
    AND (
      status = 'queued'
      OR (
        status IN ('running', 'recovering', 'verifying', 'cancel_requested')
        AND lease_expires_at IS NOT NULL
      )
    );

CREATE TABLE IF NOT EXISTS agent_runtime_controls (
  id TEXT PRIMARY KEY,
  claims_paused BOOLEAN NOT NULL DEFAULT FALSE,
  pause_reason TEXT NOT NULL DEFAULT '',
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO agent_runtime_controls (id)
VALUES ('global')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS agent_runtime_admin_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL DEFAULT '',
  request_id TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(actor_user_id, request_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_runtime_admin_events_created
  ON agent_runtime_admin_events(created_at DESC);

CREATE TABLE IF NOT EXISTS agent_run_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sequence BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, sequence)
);

CREATE TABLE IF NOT EXISTS agent_conversation_items (
  item_id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  conversation_id BIGINT,
  run_id TEXT REFERENCES agent_runs(id) ON DELETE CASCADE,
  event_cursor BIGINT,
  item_type TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  display_state TEXT NOT NULL,
  dedupe_key TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  artifact_id TEXT,
  artifact_version TEXT,
  artifact_hash TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_conversation_items_type_check CHECK (
    item_type IN ('user_turn', 'assistant_text', 'run_progress', 'safe_tool_status', 'artifact_card', 'run_gate', 'task_switch_notice', 'run_terminal', 'user_safe_error')
  ),
  CONSTRAINT agent_conversation_items_state_check CHECK (
    display_state IN ('visible', 'running', 'pending', 'resolved', 'failed', 'interrupted', 'hidden')
  ),
  CONSTRAINT agent_conversation_items_artifact_check CHECK (
    item_type <> 'artifact_card' OR (artifact_id IS NOT NULL AND artifact_version IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_conversation_items_dedupe
  ON agent_conversation_items(user_id, COALESCE(conversation_id, 0), dedupe_key);
CREATE INDEX IF NOT EXISTS idx_agent_conversation_items_timeline
  ON agent_conversation_items(user_id, conversation_id, created_at, item_id);
CREATE INDEX IF NOT EXISTS idx_agent_conversation_items_run_cursor
  ON agent_conversation_items(run_id, event_cursor);

CREATE TABLE IF NOT EXISTS agent_feature_flags (
  name TEXT PRIMARY KEY,
  purpose TEXT NOT NULL,
  owner TEXT NOT NULL,
  cohort_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  metrics_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  rollback TEXT NOT NULL,
  removal_stage TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  cohort_percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_feature_flags_percentage_check CHECK (cohort_percentage >= 0 AND cohort_percentage <= 100)
);

CREATE TABLE IF NOT EXISTS agent_run_checkpoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  snapshot_version BIGINT NOT NULL,
  fencing_token BIGINT NOT NULL,
  boundary TEXT NOT NULL,
  context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  plan_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  budgets_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  fact_refs_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_run_inputs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  request_id TEXT NOT NULL,
  input_type TEXT NOT NULL DEFAULT 'turn',
  content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  consumed_at TIMESTAMPTZ,
  UNIQUE(user_id, request_id),
  CONSTRAINT agent_run_inputs_status_check CHECK (status IN ('pending', 'consumed', 'rejected'))
);

CREATE TABLE IF NOT EXISTS agent_run_gates (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  gate_type TEXT NOT NULL DEFAULT 'approval',
  scope_hash TEXT NOT NULL,
  tool_name TEXT NOT NULL DEFAULT '',
  risk TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'pending',
  request_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  response_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  expires_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_run_gates_status_check CHECK (status IN ('pending', 'approved', 'denied', 'expired', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS agent_tool_attempts (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  attempt_sequence INTEGER NOT NULL,
  tool_name TEXT NOT NULL,
  args_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  risk TEXT NOT NULL DEFAULT 'low',
  status TEXT NOT NULL DEFAULT 'intent_recorded',
  effect_state TEXT NOT NULL DEFAULT 'not_dispatched',
  capability_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  input_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  verifier_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  owner_id TEXT,
  fencing_token BIGINT NOT NULL DEFAULT 0,
  deadline_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, idempotency_key),
  CONSTRAINT agent_tool_attempts_status_check CHECK (
    status IN ('intent_recorded', 'running', 'reconciling', 'succeeded', 'denied', 'failed', 'waiting_user', 'cancelled')
  ),
  CONSTRAINT agent_tool_attempts_effect_check CHECK (
    effect_state IN ('not_dispatched', 'not_executed', 'unknown', 'applied', 'verified', 'rolled_back')
  )
);

CREATE TABLE IF NOT EXISTS agent_background_jobs (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  tool_attempt_id TEXT REFERENCES agent_tool_attempts(id) ON DELETE SET NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  job_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  handle_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  progress_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  wake_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  lease_expires_at TIMESTAMPTZ,
  owner_id TEXT,
  fencing_token BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT agent_background_jobs_status_check CHECK (
    status IN ('queued', 'running', 'waiting', 'succeeded', 'failed', 'cancel_requested', 'cancelled')
  )
);

CREATE TABLE IF NOT EXISTS agent_run_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  event_sequence BIGINT NOT NULL,
  topic TEXT NOT NULL,
  schema_version INTEGER NOT NULL DEFAULT 1,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  attempt_count INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  locked_by TEXT,
  locked_at TIMESTAMPTZ,
  last_error TEXT NOT NULL DEFAULT '',
  delivered_at TIMESTAMPTZ,
  dead_lettered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(run_id, event_sequence, topic),
  CONSTRAINT agent_run_outbox_status_check CHECK (status IN ('pending', 'processing', 'delivered', 'dead_letter'))
);

CREATE INDEX IF NOT EXISTS idx_agent_run_events_cursor
  ON agent_run_events(run_id, sequence);
CREATE INDEX IF NOT EXISTS idx_agent_run_events_user
  ON agent_run_events(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_checkpoints_latest
  ON agent_run_checkpoints(run_id, snapshot_version DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_inputs_pending
  ON agent_run_inputs(run_id, status, id);
CREATE INDEX IF NOT EXISTS idx_agent_run_gates_pending
  ON agent_run_gates(run_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_tool_attempts_run
  ON agent_tool_attempts(run_id, attempt_sequence, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_tool_attempts_reconcile
  ON agent_tool_attempts(status, effect_state, updated_at);
CREATE INDEX IF NOT EXISTS idx_agent_background_jobs_claim
  ON agent_background_jobs(wake_at, created_at)
  WHERE status IN ('queued', 'waiting');
CREATE INDEX IF NOT EXISTS idx_agent_run_outbox_delivery
  ON agent_run_outbox(next_attempt_at, id)
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_agent_run_outbox_dead_letter
  ON agent_run_outbox(dead_lettered_at DESC)
  WHERE status = 'dead_letter';

CREATE TABLE IF NOT EXISTS agent_run_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  phase TEXT NOT NULL DEFAULT '',
  tool_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'running',
  input_summary TEXT NOT NULL DEFAULT '',
  output_summary TEXT NOT NULL DEFAULT '',
  verifier_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE agent_run_steps ADD COLUMN IF NOT EXISTS source_event_sequence BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_run_steps_event_projection
  ON agent_run_steps(run_id, source_event_sequence)
  WHERE source_event_sequence IS NOT NULL;

CREATE TABLE IF NOT EXISTS agent_run_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id),
  session_id BIGINT REFERENCES sessions(id),
  task_type TEXT NOT NULL DEFAULT '',
  agent_id TEXT NOT NULL DEFAULT '',
  verdict TEXT NOT NULL DEFAULT 'warning',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  primary_failure_type TEXT NOT NULL DEFAULT '',
  failure_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  suggested_fix TEXT NOT NULL DEFAULT '',
  eval_candidate_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  reviewer_version TEXT NOT NULL DEFAULT '',
  reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_run_reviews_verdict_check CHECK (verdict IN ('pass', 'warning', 'fail')),
  CONSTRAINT agent_run_reviews_score_check CHECK (score >= 0 AND score <= 1),
  CONSTRAINT agent_run_reviews_run_reviewer_unique UNIQUE (run_id, reviewer_version)
);

CREATE TABLE IF NOT EXISTS agent_eval_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT REFERENCES agent_run_reviews(id) ON DELETE SET NULL,
  run_id TEXT REFERENCES agent_runs(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  task_type TEXT NOT NULL DEFAULT '',
  failure_type TEXT NOT NULL DEFAULT '',
  input_summary TEXT NOT NULL DEFAULT '',
  expected_contract_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  fixture_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'candidate',
  admin_note TEXT NOT NULL DEFAULT '',
  dedupe_key TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_eval_candidates_status_check CHECK (status IN ('candidate', 'accepted', 'rejected', 'promoted'))
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_user_status ON agent_runs(user_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_session ON agent_runs(session_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_steps_run ON agent_run_steps(run_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_run ON agent_run_reviews(run_id, reviewer_version);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_user_verdict ON agent_run_reviews(user_id, verdict, reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_task_failure ON agent_run_reviews(task_type, primary_failure_type, reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_reviewed_at ON agent_run_reviews(reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_candidates_status ON agent_eval_candidates(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_candidates_failure_task ON agent_eval_candidates(failure_type, task_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_candidates_review_run ON agent_eval_candidates(review_id, run_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_eval_candidates_dedupe ON agent_eval_candidates(dedupe_key) WHERE dedupe_key <> '';

CREATE TABLE IF NOT EXISTS agent_eval_runs (
  id TEXT PRIMARY KEY,
  created_by_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  mode TEXT NOT NULL DEFAULT 'deterministic',
  status TEXT NOT NULL DEFAULT 'running',
  code_commit TEXT NOT NULL DEFAULT '',
  model_version TEXT NOT NULL DEFAULT '',
  prompt_version TEXT NOT NULL DEFAULT '',
  tool_version TEXT NOT NULL DEFAULT '',
  fixture_id TEXT NOT NULL DEFAULT '',
  fixture_version TEXT NOT NULL DEFAULT '',
  graph_version TEXT NOT NULL DEFAULT '',
  judge_version TEXT NOT NULL DEFAULT '',
  score DOUBLE PRECISION,
  hard_gate_passed BOOLEAN NOT NULL DEFAULT FALSE,
  gate_results_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  failure_evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  review_id BIGINT REFERENCES agent_run_reviews(id) ON DELETE SET NULL,
  candidate_id BIGINT REFERENCES agent_eval_candidates(id) ON DELETE SET NULL,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_eval_runs_mode_check CHECK (mode IN ('deterministic', 'staging', 'release')),
  CONSTRAINT agent_eval_runs_status_check CHECK (status IN ('running', 'passed', 'failed', 'flaky')),
  CONSTRAINT agent_eval_runs_score_check CHECK (score IS NULL OR (score >= 0 AND score <= 1))
);

CREATE INDEX IF NOT EXISTS idx_agent_eval_runs_created ON agent_eval_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_runs_fixture ON agent_eval_runs(fixture_id, fixture_version, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_runs_status ON agent_eval_runs(status, created_at DESC);

CREATE TABLE IF NOT EXISTS agent_eval_layer_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eval_run_id TEXT NOT NULL REFERENCES agent_eval_runs(id) ON DELETE CASCADE,
  layer TEXT NOT NULL,
  passed BOOLEAN NOT NULL DEFAULT FALSE,
  deterministic BOOLEAN NOT NULL DEFAULT TRUE,
  score DOUBLE PRECISION,
  failures_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(eval_run_id, layer),
  CONSTRAINT agent_eval_layer_results_layer_check CHECK (layer IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H')),
  CONSTRAINT agent_eval_layer_results_score_check CHECK (score IS NULL OR (score >= 0 AND score <= 1))
);

CREATE INDEX IF NOT EXISTS idx_agent_eval_layer_results_layer
  ON agent_eval_layer_results(layer, created_at DESC);

CREATE SEQUENCE IF NOT EXISTS cv_data_id_seq;

CREATE TABLE IF NOT EXISTS cv_data (
  id BIGINT PRIMARY KEY DEFAULT nextval('cv_data_id_seq'),
  user_id TEXT REFERENCES users(id),
  data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS resume_documents (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  version_id TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending',
  source_type TEXT NOT NULL DEFAULT 'paste',
  source_artifact_id TEXT NOT NULL DEFAULT '',
  content_hash TEXT NOT NULL DEFAULT '',
  sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  integrity_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  activated_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, version_id),
  CONSTRAINT resume_documents_status_check CHECK (status IN ('pending', 'active', 'archived'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_resume_documents_active_user
  ON resume_documents(user_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_resume_documents_user_created
  ON resume_documents(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS resume_source_artifacts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  document_id TEXT NOT NULL REFERENCES resume_documents(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL DEFAULT 'paste',
  filename TEXT NOT NULL DEFAULT '',
  mime_type TEXT NOT NULL DEFAULT 'text/plain',
  raw_text TEXT NOT NULL DEFAULT '',
  original_base64 TEXT NOT NULL DEFAULT '',
  extraction_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_hash TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_resume_source_artifacts_document
  ON resume_source_artifacts(user_id, document_id);

CREATE TABLE IF NOT EXISTS resume_chunks (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  document_id TEXT NOT NULL REFERENCES resume_documents(id) ON DELETE CASCADE,
  chunk_index INTEGER NOT NULL,
  start_offset INTEGER NOT NULL DEFAULT 0,
  end_offset INTEGER NOT NULL DEFAULT 0,
  content TEXT NOT NULL DEFAULT '',
  sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  content_hash TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(document_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_resume_chunks_document
  ON resume_chunks(user_id, document_id, chunk_index);

CREATE TABLE IF NOT EXISTS resume_drafts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  document_id TEXT REFERENCES resume_documents(id) ON DELETE SET NULL,
  artifact_id TEXT NOT NULL,
  variant_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  base_version TEXT NOT NULL DEFAULT '',
  base_hash TEXT NOT NULL DEFAULT '',
  patches_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  integrity_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, artifact_id, variant_id),
  CONSTRAINT resume_drafts_status_check CHECK (status IN ('draft', 'selected', 'applied', 'discarded'))
);

CREATE INDEX IF NOT EXISTS idx_resume_drafts_user_artifact
  ON resume_drafts(user_id, artifact_id, created_at DESC);

CREATE TABLE IF NOT EXISTS offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  monthly_salary DOUBLE PRECISION NOT NULL DEFAULT 0,
  months_per_year INTEGER NOT NULL DEFAULT 12,
  annual_bonus DOUBLE PRECISION DEFAULT 0,
  has_social_insurance INTEGER NOT NULL DEFAULT 1,
  housing_fund_rate INTEGER NOT NULL DEFAULT 7,
  options TEXT,
  probation_months INTEGER NOT NULL DEFAULT 3,
  start_date TEXT,
  other_benefits TEXT,
  location TEXT,
  level TEXT,
  employment_form TEXT NOT NULL DEFAULT 'unknown',
  employer_name TEXT,
  contract_months INTEGER,
  overtime_policy TEXT NOT NULL DEFAULT 'unknown',
  bonus_guarantee TEXT NOT NULL DEFAULT 'unknown',
  equity_type TEXT,
  equity_vesting TEXT,
  commute_minutes INTEGER,
  city_cost_level TEXT NOT NULL DEFAULT 'unknown',
  job_nature TEXT,
  benefits_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  application_id BIGINT REFERENCES applications(id),
  latest_report_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, company, role)
);

CREATE TABLE IF NOT EXISTS offer_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL DEFAULT 'Offer 对比报告',
  report_type TEXT NOT NULL DEFAULT 'comparison',
  model_version TEXT NOT NULL DEFAULT '',
  offer_id BIGINT REFERENCES offers(id),
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  verdict TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  offer_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  modules_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  red_flags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  missing_info_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  negotiation_levers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  hr_questions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  assumptions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  take_home_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  offers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  report_markdown TEXT NOT NULL DEFAULT '',
  num_offers INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_offer_reports_offer ON offer_reports(offer_id, created_at);

CREATE TABLE IF NOT EXISTS stories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL,
  situation TEXT NOT NULL DEFAULT '',
  task TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT '',
  result TEXT NOT NULL DEFAULT '',
  tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  entity_type TEXT NOT NULL,
  entity_key TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  decay_rate DOUBLE PRECISION NOT NULL DEFAULT 0.05,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, entity_type, entity_key)
);

CREATE INDEX IF NOT EXISTS idx_agent_prefs_type ON agent_preferences(entity_type);

CREATE TABLE IF NOT EXISTS session_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  session_id BIGINT DEFAULT 0,
  summary_type TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_session_memory_type ON session_memory(summary_type);

CREATE TABLE IF NOT EXISTS memory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  memory_type TEXT NOT NULL,
  canonical_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'candidate',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  importance DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  source_count INTEGER NOT NULL DEFAULT 0,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT memory_items_status_check CHECK (status IN ('candidate', 'active', 'rejected', 'archived')),
  CONSTRAINT memory_items_confidence_check CHECK (confidence >= 0 AND confidence <= 1),
  CONSTRAINT memory_items_importance_check CHECK (importance >= 0 AND importance <= 1)
);

CREATE TABLE IF NOT EXISTS memory_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  memory_item_id BIGINT REFERENCES memory_items(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL DEFAULT '',
  quote TEXT NOT NULL DEFAULT '',
  extraction_method TEXT NOT NULL DEFAULT 'unknown',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT memory_evidence_confidence_check CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE TABLE IF NOT EXISTS memory_status_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  memory_item_id BIGINT REFERENCES memory_items(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id),
  actor_user_id TEXT REFERENCES users(id),
  actor_role TEXT NOT NULL DEFAULT 'system',
  previous_status TEXT NOT NULL,
  next_status TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memory_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL DEFAULT '',
  chunk_index INTEGER NOT NULL DEFAULT 0,
  chunk_text TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  embedding_model TEXT NOT NULL DEFAULT '',
  embedding_dimension INTEGER NOT NULL DEFAULT 1536,
  embedding vector(1536),
  embedding_status TEXT NOT NULL DEFAULT 'pending',
  failure_reason TEXT NOT NULL DEFAULT '',
  retry_count INTEGER NOT NULL DEFAULT 0,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT memory_chunks_status_check CHECK (embedding_status IN ('pending', 'embedded', 'failed', 'skipped')),
  CONSTRAINT memory_chunks_dimension_check CHECK (embedding_dimension = 1536),
  CONSTRAINT memory_chunks_retry_check CHECK (retry_count >= 0),
  UNIQUE (user_id, source_type, source_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_memory_items_user_status ON memory_items(user_id, status);
CREATE INDEX IF NOT EXISTS idx_memory_items_user_type ON memory_items(user_id, memory_type);
CREATE INDEX IF NOT EXISTS idx_memory_items_recent ON memory_items(user_id, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_evidence_item ON memory_evidence(memory_item_id);
CREATE INDEX IF NOT EXISTS idx_memory_evidence_source ON memory_evidence(user_id, source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_memory_status_transitions_item ON memory_status_transitions(memory_item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_status_transitions_user ON memory_status_transitions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_user_source ON memory_chunks(user_id, source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_status ON memory_chunks(user_id, embedding_status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_recent ON memory_chunks(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS scan_queue (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  status TEXT DEFAULT 'pending',
  title_positive_json JSONB DEFAULT '[]'::jsonb,
  title_negative_json JSONB DEFAULT '[]'::jsonb,
  location_filter TEXT DEFAULT '',
  max_results INTEGER DEFAULT 50,
  companies_total INTEGER DEFAULT 0,
  companies_done INTEGER DEFAULT 0,
  jobs_found INTEGER DEFAULT 0,
  jobs_new INTEGER DEFAULT 0,
  error_log JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS scan_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id TEXT NOT NULL REFERENCES scan_queue(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  jd_id BIGINT REFERENCES jds(id),
  company TEXT NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  location TEXT DEFAULT '',
  department TEXT DEFAULT '',
  jd_snippet TEXT DEFAULT '',
  status TEXT DEFAULT 'new',
  last_error TEXT DEFAULT '',
  dedup_key TEXT NOT NULL UNIQUE,
  first_seen_at TIMESTAMPTZ DEFAULT now(),
  last_interaction_at TIMESTAMPTZ,
  discovered_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS scan_source_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id TEXT NOT NULL REFERENCES scan_queue(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  source_name TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'company_portal',
  status TEXT NOT NULL DEFAULT 'pending',
  attempted INTEGER NOT NULL DEFAULT 0,
  parsed INTEGER NOT NULL DEFAULT 0,
  matched INTEGER NOT NULL DEFAULT 0,
  inserted INTEGER NOT NULL DEFAULT 0,
  deduped INTEGER NOT NULL DEFAULT 0,
  blocked_reason TEXT NOT NULL DEFAULT '',
  error TEXT NOT NULL DEFAULT '',
  metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ DEFAULT now(),
  finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_scan_jobs_user_status ON scan_jobs(user_id, status);
CREATE INDEX IF NOT EXISTS idx_scan_jobs_scan ON scan_jobs(scan_id);
CREATE INDEX IF NOT EXISTS idx_scan_jobs_jd ON scan_jobs(jd_id);
CREATE INDEX IF NOT EXISTS idx_scan_queue_user ON scan_queue(user_id, status);
CREATE INDEX IF NOT EXISTS idx_scan_source_runs_scan ON scan_source_runs(scan_id, source_name);
CREATE INDEX IF NOT EXISTS idx_scan_source_runs_user ON scan_source_runs(user_id, status);

ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_name TEXT NOT NULL DEFAULT '';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT '';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'verified_jd';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS match_confidence TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE profiles ALTER COLUMN id SET DEFAULT nextval('profiles_id_seq');
ALTER SEQUENCE profiles_id_seq OWNED BY profiles.id;
SELECT setval('profiles_id_seq', COALESCE((SELECT MAX(id) FROM profiles), 0) + 1, false);

ALTER TABLE cv_data ALTER COLUMN id SET DEFAULT nextval('cv_data_id_seq');
ALTER SEQUENCE cv_data_id_seq OWNED BY cv_data.id;
SELECT setval('cv_data_id_seq', COALESCE((SELECT MAX(id) FROM cv_data), 0) + 1, false);

ALTER TABLE jds DROP CONSTRAINT IF EXISTS jds_report_id_fkey;
ALTER TABLE reports DROP CONSTRAINT IF EXISTS reports_report_num_key;

DO $$
BEGIN
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS role_category TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS industry_tags JSONB NOT NULL DEFAULT '[]'::jsonb;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS seniority TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'private';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS quality_score DOUBLE PRECISION NOT NULL DEFAULT 0;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS anonymized BOOLEAN NOT NULL DEFAULT FALSE;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS shared_text_redacted TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS source_hash TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS approved_by TEXT;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reports_user_report_num_key'
      AND conrelid = 'reports'::regclass
  ) THEN
    ALTER TABLE reports ADD CONSTRAINT reports_user_report_num_key UNIQUE (user_id, report_num);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_reference_resumes_visibility ON reference_resumes(visibility, status, role_category);
CREATE INDEX IF NOT EXISTS idx_reference_resumes_hash ON reference_resumes(source_hash);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'profiles_user_id_key'
      AND conrelid = 'profiles'::regclass
  ) THEN
    ALTER TABLE profiles ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cv_data_user_id_key'
      AND conrelid = 'cv_data'::regclass
  ) THEN
    ALTER TABLE cv_data ADD CONSTRAINT cv_data_user_id_key UNIQUE (user_id);
  END IF;
END $$;
