-- PostgreSQL foundation schema baseline for durable server-side data.
-- Later changes will add migration jobs, cutover logic, embeddings, and
-- stricter data-access policies.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'member',
  status TEXT NOT NULL DEFAULT 'pending',
  token_version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  approved_by TEXT,
  last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  num INTEGER NOT NULL DEFAULT 0,
  date TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'evaluated',
  pdf_generated INTEGER NOT NULL DEFAULT 0,
  report_path TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  jd_id BIGINT,
  source_url TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, company, role)
);

ALTER TABLE applications ADD COLUMN IF NOT EXISTS jd_id BIGINT;
ALTER TABLE applications ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE applications ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS application_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL DEFAULT 'note',
  from_status TEXT,
  to_status TEXT,
  note TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'system',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_application_events_user_app ON application_events(user_id, application_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_application_events_type ON application_events(user_id, event_type, created_at DESC);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  report_num INTEGER NOT NULL,
  date TEXT NOT NULL DEFAULT '',
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  archetype TEXT NOT NULL DEFAULT '',
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  legitimacy TEXT NOT NULL DEFAULT '',
  blocks_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_hash TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, report_num)
);

CREATE INDEX IF NOT EXISTS idx_reports_source_hash ON reports(source_hash);

CREATE TABLE IF NOT EXISTS jds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  source_type TEXT NOT NULL DEFAULT 'paste',
  source_url TEXT,
  body TEXT NOT NULL DEFAULT '',
  keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  report_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE SEQUENCE IF NOT EXISTS profiles_id_seq;

CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT PRIMARY KEY DEFAULT nextval('profiles_id_seq'),
  user_id TEXT REFERENCES users(id),
  data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  goals_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  history_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS profile_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  source TEXT NOT NULL DEFAULT 'dingwei',
  signal_type TEXT NOT NULL,
  content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  session_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_profile_signals_type ON profile_signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_profile_signals_created ON profile_signals(created_at);

CREATE TABLE IF NOT EXISTS reference_resumes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  name TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'paste',
  sections_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_text TEXT NOT NULL DEFAULT '',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  notes TEXT NOT NULL DEFAULT '',
  role_category TEXT NOT NULL DEFAULT '',
  industry_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  seniority TEXT NOT NULL DEFAULT '',
  visibility TEXT NOT NULL DEFAULT 'private',
  status TEXT NOT NULL DEFAULT 'active',
  quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  anonymized BOOLEAN NOT NULL DEFAULT FALSE,
  shared_text_redacted TEXT NOT NULL DEFAULT '',
  source_hash TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  approved_by TEXT REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reference_resumes_user ON reference_resumes(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS reference_resume_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_resume_id BIGINT NOT NULL REFERENCES reference_resumes(id) ON DELETE CASCADE,
  owner_user_id TEXT REFERENCES users(id),
  visibility TEXT NOT NULL DEFAULT 'private',
  status TEXT NOT NULL DEFAULT 'active',
  role_category TEXT NOT NULL DEFAULT '',
  section_type TEXT NOT NULL DEFAULT '',
  chunk_index INTEGER NOT NULL DEFAULT 0,
  chunk_text TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  embedding_model TEXT NOT NULL DEFAULT '',
  embedding_dimension INTEGER NOT NULL DEFAULT 1536,
  embedding vector(1536),
  embedding_status TEXT NOT NULL DEFAULT 'pending',
  failure_reason TEXT NOT NULL DEFAULT '',
  retry_count INTEGER NOT NULL DEFAULT 0,
  quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT reference_resume_chunks_status_check CHECK (embedding_status IN ('pending', 'embedded', 'failed', 'skipped')),
  CONSTRAINT reference_resume_chunks_dimension_check CHECK (embedding_dimension = 1536),
  UNIQUE (reference_resume_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_reference_resume_chunks_owner ON reference_resume_chunks(owner_user_id, role_category, status);
CREATE INDEX IF NOT EXISTS idx_reference_resume_chunks_shared ON reference_resume_chunks(visibility, status, role_category);
CREATE INDEX IF NOT EXISTS idx_reference_resume_chunks_embedding ON reference_resume_chunks(embedding_status, updated_at DESC);

CREATE TABLE IF NOT EXISTS reference_resume_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_resume_id BIGINT NOT NULL REFERENCES reference_resumes(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id),
  task_type TEXT NOT NULL DEFAULT 'cv_optimize',
  target_jd_id BIGINT,
  accepted BOOLEAN,
  feedback TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reference_resume_usage_resume ON reference_resume_usage(reference_resume_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reference_resume_usage_user ON reference_resume_usage(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS optimization_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  section_id TEXT NOT NULL,
  variant_type TEXT NOT NULL,
  action TEXT NOT NULL,
  original_text TEXT,
  optimized_text TEXT,
  operation TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_opt_prefs_created ON optimization_preferences(created_at);

CREATE TABLE IF NOT EXISTS resume_edit_proposals (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  section_id TEXT NOT NULL,
  base_version TEXT NOT NULL DEFAULT '',
  base_hash TEXT NOT NULL DEFAULT '',
  original_content TEXT NOT NULL DEFAULT '',
  proposed_content TEXT NOT NULL DEFAULT '',
  proposed_hash TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  risk_flags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT resume_edit_proposals_status_check CHECK (status IN ('pending', 'applied', 'discarded', 'stale', 'rolled_back'))
);

CREATE INDEX IF NOT EXISTS idx_resume_edit_proposals_user_status ON resume_edit_proposals(user_id, status, updated_at DESC);

ALTER TABLE resume_edit_proposals DROP CONSTRAINT IF EXISTS resume_edit_proposals_status_check;
ALTER TABLE resume_edit_proposals ADD CONSTRAINT resume_edit_proposals_status_check
  CHECK (status IN ('pending', 'applied', 'discarded', 'stale', 'rolled_back'));

CREATE TABLE IF NOT EXISTS news_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL,
  source_name TEXT,
  title TEXT NOT NULL,
  summary TEXT,
  url TEXT,
  published_at TIMESTAMPTZ,
  cached_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_news_cache_source ON news_cache(source);
CREATE INDEX IF NOT EXISTS idx_news_cache_cached ON news_cache(cached_at);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL DEFAULT '新对话',
  messages_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  memory_digest TEXT,
  interview_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  agent_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sessions_updated ON sessions(updated_at);

CREATE TABLE IF NOT EXISTS agent_runs (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  session_id BIGINT REFERENCES sessions(id),
  task_type TEXT NOT NULL,
  agent_id TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'planned',
  contract_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_runs_status_check CHECK (
    status IN ('planned', 'running', 'waiting_user', 'verifying', 'repairing', 'recovered', 'needs_engineering', 'succeeded', 'failed', 'rolled_back', 'cancelled')
  )
);

ALTER TABLE agent_runs DROP CONSTRAINT IF EXISTS agent_runs_status_check;
ALTER TABLE agent_runs ADD CONSTRAINT agent_runs_status_check CHECK (
  status IN ('planned', 'running', 'waiting_user', 'verifying', 'repairing', 'recovered', 'needs_engineering', 'succeeded', 'failed', 'rolled_back', 'cancelled')
);

CREATE TABLE IF NOT EXISTS agent_run_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  phase TEXT NOT NULL DEFAULT '',
  tool_name TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'running',
  input_summary TEXT NOT NULL DEFAULT '',
  output_summary TEXT NOT NULL DEFAULT '',
  verifier_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_run_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id),
  session_id BIGINT REFERENCES sessions(id),
  task_type TEXT NOT NULL DEFAULT '',
  agent_id TEXT NOT NULL DEFAULT '',
  verdict TEXT NOT NULL DEFAULT 'warning',
  score DOUBLE PRECISION NOT NULL DEFAULT 0,
  primary_failure_type TEXT NOT NULL DEFAULT '',
  failure_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  suggested_fix TEXT NOT NULL DEFAULT '',
  eval_candidate_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  reviewer_version TEXT NOT NULL DEFAULT '',
  reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_run_reviews_verdict_check CHECK (verdict IN ('pass', 'warning', 'fail')),
  CONSTRAINT agent_run_reviews_score_check CHECK (score >= 0 AND score <= 1),
  CONSTRAINT agent_run_reviews_run_reviewer_unique UNIQUE (run_id, reviewer_version)
);

CREATE TABLE IF NOT EXISTS agent_eval_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT REFERENCES agent_run_reviews(id) ON DELETE SET NULL,
  run_id TEXT REFERENCES agent_runs(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  task_type TEXT NOT NULL DEFAULT '',
  failure_type TEXT NOT NULL DEFAULT '',
  input_summary TEXT NOT NULL DEFAULT '',
  expected_contract_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  fixture_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'candidate',
  admin_note TEXT NOT NULL DEFAULT '',
  dedupe_key TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_eval_candidates_status_check CHECK (status IN ('candidate', 'accepted', 'rejected', 'promoted'))
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_user_status ON agent_runs(user_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_session ON agent_runs(session_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_steps_run ON agent_run_steps(run_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_run ON agent_run_reviews(run_id, reviewer_version);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_user_verdict ON agent_run_reviews(user_id, verdict, reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_task_failure ON agent_run_reviews(task_type, primary_failure_type, reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_reviews_reviewed_at ON agent_run_reviews(reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_candidates_status ON agent_eval_candidates(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_candidates_failure_task ON agent_eval_candidates(failure_type, task_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_eval_candidates_review_run ON agent_eval_candidates(review_id, run_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_eval_candidates_dedupe ON agent_eval_candidates(dedupe_key) WHERE dedupe_key <> '';

CREATE SEQUENCE IF NOT EXISTS cv_data_id_seq;

CREATE TABLE IF NOT EXISTS cv_data (
  id BIGINT PRIMARY KEY DEFAULT nextval('cv_data_id_seq'),
  user_id TEXT REFERENCES users(id),
  data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  company TEXT NOT NULL,
  role TEXT NOT NULL,
  monthly_salary DOUBLE PRECISION NOT NULL DEFAULT 0,
  months_per_year INTEGER NOT NULL DEFAULT 12,
  annual_bonus DOUBLE PRECISION DEFAULT 0,
  has_social_insurance INTEGER NOT NULL DEFAULT 1,
  housing_fund_rate INTEGER NOT NULL DEFAULT 7,
  options TEXT,
  probation_months INTEGER NOT NULL DEFAULT 3,
  start_date TEXT,
  other_benefits TEXT,
  location TEXT,
  level TEXT,
  employment_form TEXT NOT NULL DEFAULT 'unknown',
  employer_name TEXT,
  contract_months INTEGER,
  overtime_policy TEXT NOT NULL DEFAULT 'unknown',
  bonus_guarantee TEXT NOT NULL DEFAULT 'unknown',
  equity_type TEXT,
  equity_vesting TEXT,
  commute_minutes INTEGER,
  city_cost_level TEXT NOT NULL DEFAULT 'unknown',
  job_nature TEXT,
  benefits_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  application_id BIGINT REFERENCES applications(id),
  latest_report_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, company, role)
);

CREATE TABLE IF NOT EXISTS offer_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL DEFAULT 'Offer 对比报告',
  report_type TEXT NOT NULL DEFAULT 'comparison',
  model_version TEXT NOT NULL DEFAULT '',
  offer_id BIGINT REFERENCES offers(id),
  overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  verdict TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  offer_snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  modules_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  red_flags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  missing_info_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  negotiation_levers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  hr_questions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  assumptions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  take_home_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  offers_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  report_markdown TEXT NOT NULL DEFAULT '',
  num_offers INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_offer_reports_offer ON offer_reports(offer_id, created_at);

CREATE TABLE IF NOT EXISTS stories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  title TEXT NOT NULL,
  situation TEXT NOT NULL DEFAULT '',
  task TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT '',
  result TEXT NOT NULL DEFAULT '',
  tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agent_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  entity_type TEXT NOT NULL,
  entity_key TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  decay_rate DOUBLE PRECISION NOT NULL DEFAULT 0.05,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, entity_type, entity_key)
);

CREATE INDEX IF NOT EXISTS idx_agent_prefs_type ON agent_preferences(entity_type);

CREATE TABLE IF NOT EXISTS session_memory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT REFERENCES users(id),
  session_id BIGINT DEFAULT 0,
  summary_type TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_session_memory_type ON session_memory(summary_type);

CREATE TABLE IF NOT EXISTS memory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  memory_type TEXT NOT NULL,
  canonical_text TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'candidate',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  importance DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  source_count INTEGER NOT NULL DEFAULT 0,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT memory_items_status_check CHECK (status IN ('candidate', 'active', 'rejected', 'archived')),
  CONSTRAINT memory_items_confidence_check CHECK (confidence >= 0 AND confidence <= 1),
  CONSTRAINT memory_items_importance_check CHECK (importance >= 0 AND importance <= 1)
);

CREATE TABLE IF NOT EXISTS memory_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  memory_item_id BIGINT REFERENCES memory_items(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL DEFAULT '',
  quote TEXT NOT NULL DEFAULT '',
  extraction_method TEXT NOT NULL DEFAULT 'unknown',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT memory_evidence_confidence_check CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE TABLE IF NOT EXISTS memory_status_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  memory_item_id BIGINT REFERENCES memory_items(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES users(id),
  actor_user_id TEXT REFERENCES users(id),
  actor_role TEXT NOT NULL DEFAULT 'system',
  previous_status TEXT NOT NULL,
  next_status TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memory_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL DEFAULT '',
  chunk_index INTEGER NOT NULL DEFAULT 0,
  chunk_text TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  embedding_model TEXT NOT NULL DEFAULT '',
  embedding_dimension INTEGER NOT NULL DEFAULT 1536,
  embedding vector(1536),
  embedding_status TEXT NOT NULL DEFAULT 'pending',
  failure_reason TEXT NOT NULL DEFAULT '',
  retry_count INTEGER NOT NULL DEFAULT 0,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  embedded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT memory_chunks_status_check CHECK (embedding_status IN ('pending', 'embedded', 'failed', 'skipped')),
  CONSTRAINT memory_chunks_dimension_check CHECK (embedding_dimension = 1536),
  CONSTRAINT memory_chunks_retry_check CHECK (retry_count >= 0),
  UNIQUE (user_id, source_type, source_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_memory_items_user_status ON memory_items(user_id, status);
CREATE INDEX IF NOT EXISTS idx_memory_items_user_type ON memory_items(user_id, memory_type);
CREATE INDEX IF NOT EXISTS idx_memory_items_recent ON memory_items(user_id, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_evidence_item ON memory_evidence(memory_item_id);
CREATE INDEX IF NOT EXISTS idx_memory_evidence_source ON memory_evidence(user_id, source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_memory_status_transitions_item ON memory_status_transitions(memory_item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_status_transitions_user ON memory_status_transitions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_user_source ON memory_chunks(user_id, source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_status ON memory_chunks(user_id, embedding_status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_chunks_recent ON memory_chunks(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS scan_queue (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  status TEXT DEFAULT 'pending',
  title_positive_json JSONB DEFAULT '[]'::jsonb,
  title_negative_json JSONB DEFAULT '[]'::jsonb,
  location_filter TEXT DEFAULT '',
  max_results INTEGER DEFAULT 50,
  companies_total INTEGER DEFAULT 0,
  companies_done INTEGER DEFAULT 0,
  jobs_found INTEGER DEFAULT 0,
  jobs_new INTEGER DEFAULT 0,
  error_log JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS scan_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id TEXT NOT NULL REFERENCES scan_queue(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  jd_id BIGINT REFERENCES jds(id),
  company TEXT NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  location TEXT DEFAULT '',
  department TEXT DEFAULT '',
  jd_snippet TEXT DEFAULT '',
  status TEXT DEFAULT 'new',
  last_error TEXT DEFAULT '',
  dedup_key TEXT NOT NULL UNIQUE,
  first_seen_at TIMESTAMPTZ DEFAULT now(),
  last_interaction_at TIMESTAMPTZ,
  discovered_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS scan_source_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_id TEXT NOT NULL REFERENCES scan_queue(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  source_name TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'company_portal',
  status TEXT NOT NULL DEFAULT 'pending',
  attempted INTEGER NOT NULL DEFAULT 0,
  parsed INTEGER NOT NULL DEFAULT 0,
  matched INTEGER NOT NULL DEFAULT 0,
  inserted INTEGER NOT NULL DEFAULT 0,
  deduped INTEGER NOT NULL DEFAULT 0,
  blocked_reason TEXT NOT NULL DEFAULT '',
  error TEXT NOT NULL DEFAULT '',
  metrics_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ DEFAULT now(),
  finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_scan_jobs_user_status ON scan_jobs(user_id, status);
CREATE INDEX IF NOT EXISTS idx_scan_jobs_scan ON scan_jobs(scan_id);
CREATE INDEX IF NOT EXISTS idx_scan_jobs_jd ON scan_jobs(jd_id);
CREATE INDEX IF NOT EXISTS idx_scan_queue_user ON scan_queue(user_id, status);
CREATE INDEX IF NOT EXISTS idx_scan_source_runs_scan ON scan_source_runs(scan_id, source_name);
CREATE INDEX IF NOT EXISTS idx_scan_source_runs_user ON scan_source_runs(user_id, status);

ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_name TEXT NOT NULL DEFAULT '';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT '';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'verified_jd';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS match_confidence TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE scan_jobs ADD COLUMN IF NOT EXISTS source_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE profiles ALTER COLUMN id SET DEFAULT nextval('profiles_id_seq');
ALTER SEQUENCE profiles_id_seq OWNED BY profiles.id;
SELECT setval('profiles_id_seq', COALESCE((SELECT MAX(id) FROM profiles), 0) + 1, false);

ALTER TABLE cv_data ALTER COLUMN id SET DEFAULT nextval('cv_data_id_seq');
ALTER SEQUENCE cv_data_id_seq OWNED BY cv_data.id;
SELECT setval('cv_data_id_seq', COALESCE((SELECT MAX(id) FROM cv_data), 0) + 1, false);

ALTER TABLE jds DROP CONSTRAINT IF EXISTS jds_report_id_fkey;
ALTER TABLE reports DROP CONSTRAINT IF EXISTS reports_report_num_key;

DO $$
BEGIN
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS role_category TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS industry_tags JSONB NOT NULL DEFAULT '[]'::jsonb;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS seniority TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'private';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS quality_score DOUBLE PRECISION NOT NULL DEFAULT 0;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS anonymized BOOLEAN NOT NULL DEFAULT FALSE;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS shared_text_redacted TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS source_hash TEXT NOT NULL DEFAULT '';
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS approved_by TEXT;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
  ALTER TABLE reference_resumes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'reports_user_report_num_key'
      AND conrelid = 'reports'::regclass
  ) THEN
    ALTER TABLE reports ADD CONSTRAINT reports_user_report_num_key UNIQUE (user_id, report_num);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_reference_resumes_visibility ON reference_resumes(visibility, status, role_category);
CREATE INDEX IF NOT EXISTS idx_reference_resumes_hash ON reference_resumes(source_hash);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'profiles_user_id_key'
      AND conrelid = 'profiles'::regclass
  ) THEN
    ALTER TABLE profiles ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'cv_data_user_id_key'
      AND conrelid = 'cv_data'::regclass
  ) THEN
    ALTER TABLE cv_data ADD CONSTRAINT cv_data_user_id_key UNIQUE (user_id);
  END IF;
END $$;
