export type VerifiedActionPhase = "precheck" | "mutation" | "readBack" | "verifier" | "rollback";

export interface VerifiedActionCheck {
  phase: VerifiedActionPhase;
  ok: boolean;
  code: string;
  message: string;
}

export interface VerifiedActionEvidence {
  targetType: string;
  targetId?: string | number;
  targetField?: string;
  baseHash?: string;
  expectedHash?: string;
  readBackHash?: string;
  versionId?: string | number;
  validators: VerifiedActionCheck[];
}

export interface VerifiedActionResult<TData = unknown> {
  success: boolean;
  action: string;
  risk: "low" | "high" | "destructive";
  data: TData | null;
  precheck: VerifiedActionCheck;
  mutation?: VerifiedActionCheck;
  readBack?: VerifiedActionCheck;
  verifier: VerifiedActionCheck;
  rollback?: VerifiedActionCheck;
  evidence: VerifiedActionEvidence;
  error?: string;
}

export interface DocumentFieldValidationOptions {
  minCompactLength?: number;
  targetLabel?: string;
  expectedSectionKeywords?: string[];
  allowMarkdownHeadings?: boolean;
  allowTables?: boolean;
}

export interface DocumentFieldValidationResult {
  valid: boolean;
  checks: VerifiedActionCheck[];
  reason?: string;
}

const PLACEHOLDER_PATTERNS: Array<{ pattern: RegExp; code: string; message: string }> = [
  {
    pattern: /(?:替换为|修改为|改为)\s*[：:]?\s*$/i,
    code: "placeholder.trailing_instruction",
    message: "Content ends with a replacement instruction instead of real body text.",
  },
  {
    pattern: /(?:保持原有|保持不变|不动).{0,60}(?:替换为|修改为|改为)/i,
    code: "placeholder.keep_original_instruction",
    message: "Content is an edit instruction, not durable document content.",
  },
  {
    pattern: /\b(TODO|TBD|FIXME|placeholder|lorem ipsum)\b/i,
    code: "placeholder.generic",
    message: "Content contains generic placeholder markers.",
  },
  {
    pattern: /已更新「.+」板块到 CV|打开\s+https?:\/\/localhost/i,
    code: "placeholder.tool_result",
    message: "Content looks like a tool result or UI instruction.",
  },
  {
    pattern: /(?:达到处理上限|重新提问|被截断|补读完整|正在分析|马上给你结果)/i,
    code: "placeholder.partial_or_runtime_message",
    message: "Content contains a partial-output or runtime status message.",
  },
];

const MARKDOWN_CONTROL_PATTERNS: Array<{ pattern: RegExp; code: string; message: string }> = [
  {
    pattern: /```/,
    code: "markdown.code_fence",
    message: "Document fields must not store fenced code blocks generated by the agent.",
  },
  {
    pattern: /^\s*\|?\s*修改前\s*\|\s*修改后\s*\|\s*原因\s*\|?/im,
    code: "markdown.diff_table",
    message: "Document fields must not store modification comparison tables.",
  },
  {
    pattern: /^\s*\|.+\|\s*\n\s*\|?\s*:?-{2,}:?\s*(?:\|\s*:?-{2,}:?\s*)+\|?/m,
    code: "markdown.diff_table",
    message: "Document fields must not store markdown tables.",
  },
  {
    pattern: /^\s*#{1,6}\s+/m,
    code: "markdown.heading",
    message: "Markdown headings are not allowed in this document field.",
  },
];

export function stableContentHash(content: unknown): string {
  const normalized = typeof content === "string" ? content.replace(/\r\n/g, "\n") : JSON.stringify(content);
  let hash = 0x811c9dc5;
  const text = normalized || "";
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return `fnv1a32:${(hash >>> 0).toString(16).padStart(8, "0")}`;
}

function makeCheck(ok: boolean, code: string, message: string): VerifiedActionCheck {
  return { phase: "verifier", ok, code, message };
}

export function validateDocumentFieldContent(
  content: string,
  options: DocumentFieldValidationOptions = {},
): DocumentFieldValidationResult {
  const checks: VerifiedActionCheck[] = [];
  const normalized = content.replace(/\r/g, "").trim();
  const compact = normalized.replace(/\s/g, "");
  const targetLabel = options.targetLabel || "document field";

  const minLength = options.minCompactLength ?? 1;
  checks.push(makeCheck(compact.length >= minLength, "content.min_length", `${targetLabel} compact length >= ${minLength}`));

  for (const item of PLACEHOLDER_PATTERNS) {
    checks.push(makeCheck(!item.pattern.test(normalized), item.code, item.message));
  }

  for (const item of MARKDOWN_CONTROL_PATTERNS) {
    if (item.code === "markdown.heading" && options.allowMarkdownHeadings) continue;
    if (item.code === "markdown.diff_table" && options.allowTables) continue;
    checks.push(makeCheck(!item.pattern.test(normalized), item.code, item.message));
  }

  if (options.expectedSectionKeywords?.length) {
    const hasExpectedKeyword = options.expectedSectionKeywords.some((keyword) => normalized.includes(keyword));
    checks.push(makeCheck(hasExpectedKeyword, "content.target_section_keyword", `${targetLabel} contains an expected section keyword.`));
  }

  const failed = checks.find((check) => !check.ok);
  return {
    valid: !failed,
    checks,
    reason: failed?.message,
  };
}

export function buildVerifiedActionFailure<TData = unknown>(input: {
  action: string;
  targetType: string;
  risk?: "low" | "high" | "destructive";
  precheck?: VerifiedActionCheck;
  verifier?: VerifiedActionCheck;
  checks?: VerifiedActionCheck[];
  error: string;
  data?: TData | null;
}): VerifiedActionResult<TData> {
  const precheck = input.precheck || {
    phase: "precheck",
    ok: false,
    code: "precheck.failed",
    message: input.error,
  };
  const verifier = input.verifier || {
    phase: "verifier",
    ok: false,
    code: "verifier.failed",
    message: input.error,
  };
  return {
    success: false,
    action: input.action,
    risk: input.risk || "high",
    data: input.data ?? null,
    precheck,
    verifier,
    evidence: {
      targetType: input.targetType,
      validators: input.checks || [precheck, verifier],
    },
    error: input.error,
  };
}

export function buildVerifiedActionSuccess<TData = unknown>(input: {
  action: string;
  targetType: string;
  targetId?: string | number;
  targetField?: string;
  risk?: "low" | "high" | "destructive";
  data: TData;
  expectedContent?: unknown;
  readBackContent?: unknown;
  versionId?: string | number;
  checks?: VerifiedActionCheck[];
}): VerifiedActionResult<TData> {
  const expectedHash = input.expectedContent === undefined ? undefined : stableContentHash(input.expectedContent);
  const readBackHash = input.readBackContent === undefined ? undefined : stableContentHash(input.readBackContent);
  const hashesMatch = expectedHash === undefined || readBackHash === expectedHash;
  const readBack: VerifiedActionCheck = {
    phase: "readBack",
    ok: hashesMatch,
    code: hashesMatch ? "read_back.match" : "read_back.mismatch",
    message: hashesMatch ? "Read-back content matches expected content." : "Read-back content does not match expected content.",
  };
  const validatorChecks = input.checks || [];
  const validatorsPass = validatorChecks.every((check) => check.ok);
  const verifier: VerifiedActionCheck = {
    phase: "verifier",
    ok: hashesMatch && validatorsPass,
    code: hashesMatch && validatorsPass ? "verifier.passed" : "verifier.failed",
    message: hashesMatch && validatorsPass ? "Verified action passed." : "Verified action failed.",
  };

  return {
    success: verifier.ok,
    action: input.action,
    risk: input.risk || "high",
    data: input.data,
    precheck: {
      phase: "precheck",
      ok: true,
      code: "precheck.passed",
      message: "Preconditions passed.",
    },
    mutation: {
      phase: "mutation",
      ok: true,
      code: "mutation.applied",
      message: "Mutation applied.",
    },
    readBack,
    verifier,
    evidence: {
      targetType: input.targetType,
      targetId: input.targetId,
      targetField: input.targetField,
      expectedHash,
      readBackHash,
      versionId: input.versionId,
      validators: validatorChecks,
    },
    error: verifier.ok ? undefined : verifier.message,
  };
}
